//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.MVC.CustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer_", Namespace="http://schemas.datacontract.org/2004/07/Demo.MVC.Services")]
    [System.SerializableAttribute()]
    public partial class Customer_ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CreditLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((this.ContactNoField.Equals(value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CreditLimit {
            get {
                return this.CreditLimitField;
            }
            set {
                if ((this.CreditLimitField.Equals(value) != true)) {
                    this.CreditLimitField = value;
                    this.RaisePropertyChanged("CreditLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyEmail", Namespace="http://schemas.datacontract.org/2004/07/Demo.EmailSender")]
    [System.SerializableAttribute()]
    public partial class MyEmail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
        Demo.MVC.CustomerService.AddCustomerResponse AddCustomer(Demo.MVC.CustomerService.AddCustomerRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
        System.Threading.Tasks.Task<Demo.MVC.CustomerService.AddCustomerResponse> AddCustomerAsync(Demo.MVC.CustomerService.AddCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/addCustomerWithEmail", ReplyAction="http://tempuri.org/ICustomerService/addCustomerWithEmailResponse")]
        Demo.MVC.CustomerService.addCustomerWithEmailResponse addCustomerWithEmail(Demo.MVC.CustomerService.addCustomerWithEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/addCustomerWithEmail", ReplyAction="http://tempuri.org/ICustomerService/addCustomerWithEmailResponse")]
        System.Threading.Tasks.Task<Demo.MVC.CustomerService.addCustomerWithEmailResponse> addCustomerWithEmailAsync(Demo.MVC.CustomerService.addCustomerWithEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/getCustomer", ReplyAction="http://tempuri.org/ICustomerService/getCustomerResponse")]
        Demo.MVC.CustomerService.Customer_ getCustomer(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/getCustomer", ReplyAction="http://tempuri.org/ICustomerService/getCustomerResponse")]
        System.Threading.Tasks.Task<Demo.MVC.CustomerService.Customer_> getCustomerAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/getCustomers", ReplyAction="http://tempuri.org/ICustomerService/getCustomersResponse")]
        Demo.MVC.CustomerService.Customer_[] getCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/getCustomers", ReplyAction="http://tempuri.org/ICustomerService/getCustomersResponse")]
        System.Threading.Tasks.Task<Demo.MVC.CustomerService.Customer_[]> getCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteCustomer", ReplyAction="http://tempuri.org/ICustomerService/DeleteCustomerResponse")]
        Demo.MVC.CustomerService.DeleteCustomerResponse DeleteCustomer(Demo.MVC.CustomerService.DeleteCustomerRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteCustomer", ReplyAction="http://tempuri.org/ICustomerService/DeleteCustomerResponse")]
        System.Threading.Tasks.Task<Demo.MVC.CustomerService.DeleteCustomerResponse> DeleteCustomerAsync(Demo.MVC.CustomerService.DeleteCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomer", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerResponse")]
        Demo.MVC.CustomerService.UpdateCustomerResponse UpdateCustomer(Demo.MVC.CustomerService.UpdateCustomerRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomer", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<Demo.MVC.CustomerService.UpdateCustomerResponse> UpdateCustomerAsync(Demo.MVC.CustomerService.UpdateCustomerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Demo.MVC.CustomerService.Customer_ customer;
        
        public AddCustomerRequest() {
        }
        
        public AddCustomerRequest(Demo.MVC.CustomerService.Customer_ customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddCustomerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errMsg;
        
        public AddCustomerResponse() {
        }
        
        public AddCustomerResponse(bool AddCustomerResult, string errMsg) {
            this.AddCustomerResult = AddCustomerResult;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCustomerWithEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class addCustomerWithEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Demo.MVC.CustomerService.Customer_ customer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Demo.MVC.CustomerService.MyEmail myEmail;
        
        public addCustomerWithEmailRequest() {
        }
        
        public addCustomerWithEmailRequest(Demo.MVC.CustomerService.Customer_ customer, Demo.MVC.CustomerService.MyEmail myEmail) {
            this.customer = customer;
            this.myEmail = myEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCustomerWithEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class addCustomerWithEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool addCustomerWithEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errMsg;
        
        public addCustomerWithEmailResponse() {
        }
        
        public addCustomerWithEmailResponse(bool addCustomerWithEmailResult, string errMsg) {
            this.addCustomerWithEmailResult = addCustomerWithEmailResult;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Demo.MVC.CustomerService.Customer_ customer;
        
        public DeleteCustomerRequest() {
        }
        
        public DeleteCustomerRequest(Demo.MVC.CustomerService.Customer_ customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteCustomerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errMsg;
        
        public DeleteCustomerResponse() {
        }
        
        public DeleteCustomerResponse(bool DeleteCustomerResult, string errMsg) {
            this.DeleteCustomerResult = DeleteCustomerResult;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Demo.MVC.CustomerService.Customer_ customer;
        
        public UpdateCustomerRequest() {
        }
        
        public UpdateCustomerRequest(Demo.MVC.CustomerService.Customer_ customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateCustomerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errMsg;
        
        public UpdateCustomerResponse() {
        }
        
        public UpdateCustomerResponse(bool UpdateCustomerResult, string errMsg) {
            this.UpdateCustomerResult = UpdateCustomerResult;
            this.errMsg = errMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : Demo.MVC.CustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<Demo.MVC.CustomerService.ICustomerService>, Demo.MVC.CustomerService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.MVC.CustomerService.AddCustomerResponse Demo.MVC.CustomerService.ICustomerService.AddCustomer(Demo.MVC.CustomerService.AddCustomerRequest request) {
            return base.Channel.AddCustomer(request);
        }
        
        public bool AddCustomer(Demo.MVC.CustomerService.Customer_ customer, out string errMsg) {
            Demo.MVC.CustomerService.AddCustomerRequest inValue = new Demo.MVC.CustomerService.AddCustomerRequest();
            inValue.customer = customer;
            Demo.MVC.CustomerService.AddCustomerResponse retVal = ((Demo.MVC.CustomerService.ICustomerService)(this)).AddCustomer(inValue);
            errMsg = retVal.errMsg;
            return retVal.AddCustomerResult;
        }
        
        public System.Threading.Tasks.Task<Demo.MVC.CustomerService.AddCustomerResponse> AddCustomerAsync(Demo.MVC.CustomerService.AddCustomerRequest request) {
            return base.Channel.AddCustomerAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.MVC.CustomerService.addCustomerWithEmailResponse Demo.MVC.CustomerService.ICustomerService.addCustomerWithEmail(Demo.MVC.CustomerService.addCustomerWithEmailRequest request) {
            return base.Channel.addCustomerWithEmail(request);
        }
        
        public bool addCustomerWithEmail(Demo.MVC.CustomerService.Customer_ customer, Demo.MVC.CustomerService.MyEmail myEmail, out string errMsg) {
            Demo.MVC.CustomerService.addCustomerWithEmailRequest inValue = new Demo.MVC.CustomerService.addCustomerWithEmailRequest();
            inValue.customer = customer;
            inValue.myEmail = myEmail;
            Demo.MVC.CustomerService.addCustomerWithEmailResponse retVal = ((Demo.MVC.CustomerService.ICustomerService)(this)).addCustomerWithEmail(inValue);
            errMsg = retVal.errMsg;
            return retVal.addCustomerWithEmailResult;
        }
        
        public System.Threading.Tasks.Task<Demo.MVC.CustomerService.addCustomerWithEmailResponse> addCustomerWithEmailAsync(Demo.MVC.CustomerService.addCustomerWithEmailRequest request) {
            return base.Channel.addCustomerWithEmailAsync(request);
        }
        
        public Demo.MVC.CustomerService.Customer_ getCustomer(int Id) {
            return base.Channel.getCustomer(Id);
        }
        
        public System.Threading.Tasks.Task<Demo.MVC.CustomerService.Customer_> getCustomerAsync(int Id) {
            return base.Channel.getCustomerAsync(Id);
        }
        
        public Demo.MVC.CustomerService.Customer_[] getCustomers() {
            return base.Channel.getCustomers();
        }
        
        public System.Threading.Tasks.Task<Demo.MVC.CustomerService.Customer_[]> getCustomersAsync() {
            return base.Channel.getCustomersAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.MVC.CustomerService.DeleteCustomerResponse Demo.MVC.CustomerService.ICustomerService.DeleteCustomer(Demo.MVC.CustomerService.DeleteCustomerRequest request) {
            return base.Channel.DeleteCustomer(request);
        }
        
        public bool DeleteCustomer(Demo.MVC.CustomerService.Customer_ customer, out string errMsg) {
            Demo.MVC.CustomerService.DeleteCustomerRequest inValue = new Demo.MVC.CustomerService.DeleteCustomerRequest();
            inValue.customer = customer;
            Demo.MVC.CustomerService.DeleteCustomerResponse retVal = ((Demo.MVC.CustomerService.ICustomerService)(this)).DeleteCustomer(inValue);
            errMsg = retVal.errMsg;
            return retVal.DeleteCustomerResult;
        }
        
        public System.Threading.Tasks.Task<Demo.MVC.CustomerService.DeleteCustomerResponse> DeleteCustomerAsync(Demo.MVC.CustomerService.DeleteCustomerRequest request) {
            return base.Channel.DeleteCustomerAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.MVC.CustomerService.UpdateCustomerResponse Demo.MVC.CustomerService.ICustomerService.UpdateCustomer(Demo.MVC.CustomerService.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public bool UpdateCustomer(Demo.MVC.CustomerService.Customer_ customer, out string errMsg) {
            Demo.MVC.CustomerService.UpdateCustomerRequest inValue = new Demo.MVC.CustomerService.UpdateCustomerRequest();
            inValue.customer = customer;
            Demo.MVC.CustomerService.UpdateCustomerResponse retVal = ((Demo.MVC.CustomerService.ICustomerService)(this)).UpdateCustomer(inValue);
            errMsg = retVal.errMsg;
            return retVal.UpdateCustomerResult;
        }
        
        public System.Threading.Tasks.Task<Demo.MVC.CustomerService.UpdateCustomerResponse> UpdateCustomerAsync(Demo.MVC.CustomerService.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
    }
}
